version: "3.9"
services:
  db:
    image: postgres:15.3
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - nod_network

volumes:
  db_data:

networks:
  nod_network:
    driver: bridge