"""Create products table

Revision ID: 0e6021a98dc4
Revises: bfa00ee39469
Create Date: 2025-03-18 21:26:53.470318

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "0e6021a98dc4"
down_revision: Union[str, None] = "bfa00ee39469"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
