"""Create product

Revision ID: bfa00ee39469
Revises:
Create Date: 2025-03-18 19:40:15.824849
"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "bfa00ee39469"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
